## 1️⃣ Why NumPy? (Speed vs Python Lists)
Python lists:
- Store elements in different memory locations
- Can store mixed data types
- Each element is a Python object
- Operations run through Python interpreter (slow for large data)

NumPy:
- Stores data in contiguous memory
- Same datatype
- Implemented in C
- Supports vectorized operations (very fast)


In [ ]:
# Python list addition (slow approach)
a = [1,2,3]
b = [4,5,6]
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)

In [ ]:
# NumPy vectorized addition (fast approach)
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Array a:",a)
print("Array b:",b)
print(a + b)

x=10

In [ ]:
# Large scale computation example
a = np.arange(1000000)
b = np.arange(1000000)

c = a + b
print('Computation completed')

## 2️⃣ What is ndarray?
ndarray = N-dimensional array.
- 1D → Vector
- 2D → Matrix
- 3D → Tensor
- Fixed size & same datatype


In [2]:
import numpy as np

In [3]:
#1D array  np.array([list])
a = np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
b=np.array(8)
print(b)
print(type(b))

In [5]:
# 2D array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


##3️⃣ Creating Arrays
np.array() → Converts a Python list or tuple into a NumPy array for fast computations.

np.zeros() → Creates a NumPy array filled entirely with zeros.

np.ones() → Creates a NumPy array filled entirely with ones.

np.arange() → Generates a NumPy array with evenly spaced values within a specified range (step-defined).

np.linspace() → Generates a NumPy array with a specified number of evenly spaced values between two endpoints.

In [ ]:
print(np.zeros((2,3)))
print(np.ones((3,2)))
print(np.arange(1,13,2))
print(np.linspace(0,1,5))
print(np.eye(4,4))

In [6]:
print(np.zeros((3)))

[0. 0. 0.]


In [7]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(np.ones((5)))

[1. 1. 1. 1. 1.]


In [9]:
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [12]:
print(np.linspace(10,50,5))

[10. 20. 30. 40. 50.]


In [13]:
print(np.linspace(0,40,4))

[ 0.         13.33333333 26.66666667 40.        ]


In [ ]:
print(np.linspace(0,60,5))

In [ ]:

import numpy as np
print(np.zeros((3)))# 1D array with 3 elements 
print(np.zeros((3,3)))# 2D array with 3 rows and 3 columns

In [ ]:
print(np.ones((3)))
print(np.ones((3,2)))

In [ ]:
print(np.arange(11))

In [ ]:
print(np.arange(1,11))

In [ ]:
print(np.arange(1,11,2))

In [ ]:
print(np.arange(2,11,2))

In [ ]:
print(np.arange(1,13,2))

In [ ]:
print(np.arange(0,20,2))

In [ ]:
print(np.arange(0,20,3))

In [ ]:
print(np.arange(0,20,1))

In [ ]:
print(np.linspace(0,1,3))

In [ ]:
print(np.linspace(0,100,3))

In [ ]:
print(np.linspace(0,9,3))

In [ ]:
print(np.linspace(0,1,5))

In [ ]:
print(np.linspace(0,100,5))

In [ ]:
print(np.linspace(0,15,4))

In [ ]:
x=np.arange(11)
print(x)

In [ ]:
x1=np.arange(1,11)
print(x1)

In [ ]:
x2=np.arange(2,11,2)
print(x2)

## 4️⃣ Array Attributes
ndim → Returns the number of dimensions (axes) of the array.

shape → Returns the dimensions of the array as a tuple (rows, columns, …).

size → Returns the total number of elements in the array.

dtype → Returns the data type of the array elements.

itemsize → Returns the memory size (in bytes) of each array element.


### 1 Dimensional array

In [14]:
a1=np.array(['a','b','c','d'])

print("Array:",a1)
print("Dimension:",a1.ndim)
print("Shape:",a1.shape)
print("Total elements:",a1.size)
print("Data type:",a1.dtype)
print("Memory size:",a1.itemsize)

Array: ['a' 'b' 'c' 'd']
Dimension: 1
Shape: (4,)
Total elements: 4
Data type: <U1
Memory size: 4


###  Dimensional array

In [ ]:
a = np.array([1,2,3])
print('number of dimension:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('dtype:', a.dtype)
print('itemsize:', a.itemsize)

In [15]:
a = np.array([[1,2,3],[4,5,6]])
print('number of dimension:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('dtype:', a.dtype)
print('itemsize:', a.itemsize)

number of dimension: 2
shape: (2, 3)
size: 6
dtype: int32
itemsize: 4


## 5️⃣ Basic Element-wise Operations


In [ ]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print('Addition:', a + b)
print('Subtraction:', a - b)
print('Multiplication:', a * b)
print('Division:', a / b)
print('Floor Division:', a // b)
print('Scalar Addition:', a + 5)
print('Scalar Multiplication:', a * 5)

## Practice Questions

1️⃣ Create a 5x7 matrix filled with 1.

2️⃣ Create an array from 50 to 100 with step 5.

3️⃣ Create 7 evenly spaced numbers between 10 and 20.

4️⃣ Print ndim, shape, dtype of a 3x4 matrix.

5️⃣ Multiply two arrays element-wise.

6. create identity matrix of size 8


In [ ]:
[7 14 21 28 35 42]

In [ ]:
x=np.linspace(7,42,6)
print(x)

In [ ]:
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]

l1=np.array(l)
print(l1)

In [ ]:
print(l1.ndim)

In [ ]:
l2=np.arange(1,17)
print(l2)

In [ ]:
print(l2.ndim)

In [ ]:
l3=l2.reshape((4,4))
print(l3)

In [ ]:
l4=l2.reshape((2,8))
l5=l2.reshape((1,16))
print(l4)
print(l5)

In [ ]:
print(l5.ndim)

In [ ]:
l4=l2.reshape((8,2))
print(l4)

In [ ]:
#3d array

three_d=[[[1,2],[3,4]]]
th=np.array(three_d)
print(th)
print(th.ndim)


In [ ]:
print(th.shape)

In [ ]:
t=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

t1=np.array(t)
print(t1)
print(t1.ndim)

In [ ]:
print(t1.shape)

In [ ]:
l2=np.arange(1,17)
print(l2)
print()
l3=l2.reshape(2,2,4)
print(l3)

In [ ]:
l1=np.arange(1,17)
print(l1)
print()
print("***********")
l2=l1.reshape(4,4)
print(l2)
print()

print("***********")
l3=l1.reshape(2,2,4)
print(l3)

In [ ]:
print(l1[0])
print(l1[8])

In [ ]:
print(l2[1,1])
print(l2[2,2])

In [ ]:
print(l3[1,1,1])

In [ ]:
print(l3[0,1,2])

In [16]:
a1=np.arange(11)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [17]:
a2=np.arange(1,11)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
odd=np.arange(1,50,2)
even=np.arange(2,51,2)


print(odd)
print(even)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [22]:
n=np.arange(1,17)
print(n)
print(n.ndim)
print(n.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
(16,)


In [23]:
n2=n.reshape((1,16))
print(n2)
print(n2.ndim)
print(n2.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]
2
(1, 16)


In [30]:
n2=n.reshape((4,4))
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### n3=n.reshape((16,1))
print(n3)
print(n3.ndim)
print(n3.shape)

In [25]:
n4=n.reshape((2,2,4))
print(n4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [26]:
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [27]:
print(n[0])

1


In [28]:
print(n[10])

11


In [31]:
print(n2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [32]:
print(n2[1])

[5 6 7 8]


In [33]:
print(n2[1][2])

7


In [34]:
print(n2[2][2])

11


In [36]:
print(n2[2,2])

11


In [37]:
print(n2[:,0])

[ 1  5  9 13]


In [38]:
print(n4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [39]:
print(n4[1,1,2])

15


In [40]:
print(n4[0,1,2])

7


In [42]:
n5=n.reshape((4,2,2))
print(n5)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [43]:
print(n5[2,1,1])

12
