<a href="https://colab.research.google.com/github/sana-123-githu/internship/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd
data = ['A','B','C','D']
ser = pd.Series(data)
print(ser)
print(type(ser))

0    A
1    B
2    C
3    D
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
import numpy as np
import pandas as pd
data=np.arange(21,26)
ser = pd.Series(data)
print(ser)



0    21
1    22
2    23
3    24
4    25
dtype: int64


In [ ]:
import pandas as pd
data = {'A':100,'B':200,'C':300}
ser = pd.Series(data)
print(ser)

A    100
B    200
C    300
dtype: int64


In [ ]:
import pandas as pd
data =['apple','orange','banana']
df =pd.DataFrame(data)
print(df)
print()
print(type(df))

        0
0   apple
1  orange
2  banana

<class 'pandas.core.frame.DataFrame'>


In [ ]:
import numpy as np
import pandas as pd
data=np.arange(1,65)
print(data)
n1=data.reshape((8,8))
print(n1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [ ]:
import pandas as pd

data = {
    'name': ['anu', 'veena', 'meera', 'sana', 'cenna', 'abhi',
             'yasee', 'nevin', 'kiran', 'meenu', 'faby', 'sappu'],

    'course': ['MBA', 'BCA', 'MCA', 'MTech', 'BTech', 'BBA',
               'Bcom', 'Mcom', 'CA', 'ACCA', 'CMA', 'CS'],

    'score': [90, 87, 56, 70, 89, 28, 10, 29, 39, 38, 46, 74],

    'city': ['Tokyo', 'New York', 'London', 'Paris', 'Sydney', 'Dubai',
             'Singapore', 'Mumbai', 'Toronto', 'Berlin', 'Cape Town', 'Chennai'],

    'blood group': ['A', 'B', 'AB+', 'AB-', 'A+', 'O+',
                    'O-', 'A-', 'B+', 'B-', 'AB+', 'O+']
}

df = pd.DataFrame(data)
print(df)




     name course  score       city blood group
0     anu    MBA     90      Tokyo           A
1   veena    BCA     87   New York           B
2   meera    MCA     56     London         AB+
3    sana  MTech     70      Paris         AB-
4   cenna  BTech     89     Sydney          A+
5    abhi    BBA     28      Dubai          O+
6   yasee   Bcom     10  Singapore          O-
7   nevin   Mcom     29     Mumbai          A-
8   kiran     CA     39    Toronto          B+
9   meenu   ACCA     38     Berlin          B-
10   faby    CMA     46  Cape Town         AB+
11  sappu     CS     74    Chennai          O+


In [ ]:
df.shape

(12, 5)

In [ ]:
df.size

60

In [ ]:
df.head()

,name,course,score,city,blood group
0,anu,MBA,90,Tokyo,A
1,veena,BCA,87,New York,B
2,meera,MCA,56,London,AB+
3,sana,MTech,70,Paris,AB-
4,cenna,BTech,89,Sydney,A+


In [ ]:
df.tail()

,name,course,score,city,blood group
7,nevin,Mcom,29,Mumbai,A-
8,kiran,CA,39,Toronto,B+
9,meenu,ACCA,38,Berlin,B-
10,faby,CMA,46,Cape Town,AB+
11,sappu,CS,74,Chennai,O+


In [ ]:
df.columns

Index(['name', 'course', 'score', 'city', 'blood group'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   name         12 non-null     object
 1   course       12 non-null     object
 2   score        12 non-null     int64 
 3   city         12 non-null     object
 4   blood group  12 non-null     object
dtypes: int64(1), object(4)
memory usage: 612.0+ bytes


In [ ]:
df.describe()

,score
count,12.000000
mean,54.666667
std,27.046537
min,10.000000
25%,35.750000
50%,51.000000
75%,77.250000
max,90.000000
